apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-services
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: cluster-resources/core-services
    repoURL: 'git@github.com:jseely/talos-config.git'
    targetRevision: HEAD
  destination:
    namespace: core-services
    server: 'https://kubernetes.default.svc'