apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-applications
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: cluster-resources/applications
    repoURL: 'git@github.com:jseely/talos-config.git'
    targetRevision: HEAD
  destination:
    namespace: cluster-applications
    server: 'https://kubernetes.default.svc'