apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.2/manifests/core-install.yaml
# TODO: Figure out how to get this patch working
# patches:
#   - target:
#       kind: ConfigMap
#       name: argocd-cm
#     patch: |
#       apiVersion: v1
#       kind: ConfigMap
#       data:
#         resource.exclusions: "- apiGroups:\\n    - cilium.io\\n  kinds:\\n    - CiliumIdentity\\n  clusters:\\n    - '*'"
