apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-conf
spec:
  config: '{
    "cniVersion": "0.3.0",
    "type": "bridge",
    "master": "eth0",
    "mode": "bridge",
    "ipam": {
      "type": "host-local",
      "subnet": "10.0.144.0/24",
      "rangeStart": "10.0.144.201",
      "rangeEnd": "10.0.144.250",
      "routes": [
        {"dst": "0.0.0.0/0"}
      ],
      "gateway": "10.0.144.1"
    }
  }'