---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: cilium
spec:
  controllerName: io.cilium/gateway-controller
  description: The default Cilium GatewayClass
  parametersRef:
    group: cilium.io
    kind: CiliumGatewayClassConfig
    name: cilium-gateway-config
    namespace: core-services
---
apiVersion: cilium.io/v2alpha1
kind: CiliumGatewayClassConfig
metadata:
  name: cilium-gateway-config
spec:
  service:
    type: LoadBalancer
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium-gateway
spec:
  gatewayClassName: cilium
  addresses:
  - value: "10.0.144.99"
  listeners:
  - name: http
    hostname: "*.seely.dev"
    protocol: HTTP
    port: 80
    allowRoutes:
      namespaces:
        from: ALL
  - name: https
    hostname: "*.seely.dev"
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      certificateRefs:
      - name: cilium-gateway-cert
    allowRoutes:
      namespaces:
        from: ALL