apiVersion: v1
kind: Namespace
metadata:
  name: gateway
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cilium-gateway-cert
  namespace: gateway
spec:
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - "*.seely.dev"
  secretName: cilium-gateway-cert
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium-gateway
  namespace: gateway
spec:
  gatewayClassName: cilium
  listeners:
  - name: https
    hostname: "*.seely.dev"
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      certificateRefs:
      - name: cilium-gateway-cert
    allowedRoutes:
      namespaces:
        from: All
