apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/nginx/nginx-gateway-fabric/config/crd/gateway-api/experimental?ref=v1.6.2
- https://raw.githubusercontent.com/nginx/nginx-gateway-fabric/v1.6.2/deploy/crds.yaml
- https://raw.githubusercontent.com/nginx/nginx-gateway-fabric/v1.6.2/deploy/experimental/deploy.yaml
- nginx-gateway.yaml
- https://github.com/pl4nty/cloudflare-kubernetes-gateway//config/default?ref=v0.8.1
- cloudflare-secret.yaml
- cloudflared-gateway.yaml