apiVersion: v1
kind: Namespace
metadata:
  name: gateway
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-gateway-cert
  namespace: gateway
spec:
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - "*.seely.dev"
  secretName: nginx-gateway-cert
---
apiVersion: gateway.nginx.org/v1alpha1
kind: ClientSettingsPolicy
metadata:
  name: nginx-gateway-client-settings
  namespace: gateway
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: nginx-gateway
  body:
    maxSize: "0"
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: nginx-gateway
  namespace: gateway
spec:
  gatewayClassName: nginx
  listeners:
  - name: https
    hostname: "*.seely.dev"
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      certificateRefs:
      - name: nginx-gateway-cert
    allowedRoutes:
      namespaces:
        from: All
