apiVersion: v1
kind: Namespace
metadata:
  name: dns
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: dns-server-dv
  namespace: dns
spec:
  source:
    registry:
      url: reg.seely.dev/dns-etc-img
  storage:
    accessModes:
      - ReadWriteOnce
    storageClassName: local-path
    resources:
      requests:
        storage: 25Gi
