apiVersion: v1
kind: Namespace
metadata:
  name: dns
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: dns-server-dv
  namespace: dns
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
spec:
  source:
    registry:
      url: docker://reg.seely.dev/dns-etc-img
  storage:
    accessModes:
      - ReadWriteOnce
    storageClassName: local-path
    resources:
      requests:
        storage: 25Gi
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: dns-etc-vm
  namespace: dns
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        vmi.kubevirt.io/name: dns-etc-vm
    spec:
      domain:
        devices:
          disks:
            - name: disk0
              disk: {}
        cpu:
          cores: 2
          threads: 2
          sockets: 1
        resources:
          requests:
            memory: 2Gi
      volumes:
        - name: disk0
          dataVolume:
            name: dns-server-dv
---
apiVersion: v1
kind: Service
metadata:
  name: dns-etc-vm
  namespace: dns
spec:
  selector:
    vmi.kubevirt.io/name: dns-etc-vm
  type: LoadBalancer
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dns
    - port: 80
      targetPort: 80
      name: http
    - port: 22
      targetPort: 22
      name: ssh
