apiVersion: v1
kind: Pod
metadata:
  name: pihole
  namespace: dns
  labels:
    app: pihole
spec:
  containers:
    - name: pihole
      image: pihole/pihole
      ports:
        - containerPort: 53:q

      resources:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 1Gi
          cpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: udp-echo
spec:
  selector:
    app: udp-echo
  type: LoadBalancer
  ports:
    - port: 1234
      targetPort: 1234
      protocol: UDP
      name: echo
