apiVersion: v1
kind: Pod
metadata:
  name: udp-echo
  labels:
    app: udp-echo
spec:
  containers:
    - name: udp-echo
      image: reg.seely.dev/udp-server
      ports:
        - containerPort: 1234
      resources:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 1Gi
          cpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: udp-echo
spec:
  selector:
    app: udp-echo
  type: LoadBalancer
  ports:
    - port: 1234
      targetPort: 1234
      protocol: UDP
      name: echo
