apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: rpi
  namespace: dns
spec:
  parentRefs:
    - name: cilium-gateway
      namespace: gateway
  hostnames:
    - rpi.seely.dev
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
        - name: pihole-web
          port: 80
