apiVersion: v1
kind: Namespace
metadata:
  name: registry
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
  namespace: registry
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: registry
  namespace: registry
  labels:
    app: registry
spec:
  containers:
    - name: registry
      image: registry:2
      resources:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 1Gi
          cpu: 1
      ports:
        - containerPort: 5000
      volumeMounts:
        - mountPath: /var/lib/registry
          name: registry-storage
  volumes:
    - name: registry-storage
      persistentVolumeClaim:
        claimName: registry-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: registry-service
  namespace: registry
spec:
  selector:
    app: registry
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: registry
  namespace: registry
spec:
  parentRefs:
    - name: nginx-gateway
      namespace: gateway
  hostnames:
    - reg.seely.dev
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
        - name: registry-service
          port: 80
