apiVersion: v1
kind: Service
metadata:
  name: cdi-uploadproxy-loadbalancer
  namespace: cdi
  labels:
    cdi.kubevirt.io: cdi-uploadproxy
spec:
  type: LoadBalancer
  ports:
    - targetPort: 8443
      port: 443
      protocol: TCP
  selector:
    cdi.kubevirt.io: cdi-uploadproxy
