apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/kubevirt/kubevirt/releases/download/v1.5.0/kubevirt-operator.yaml
- kubevirt.yaml
- https://github.com/kubevirt/containerized-data-importer/releases/download/v1.61.5/cdi-cr.yaml
- https://github.com/kubevirt/containerized-data-importer/releases/download/v1.61.5/cdi-operator.yaml
- cdi-uploadproxy-endpoint.yaml
